# Generated by Django 2.0.6 on 2018-09-02 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created-date')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created-at')),
                ('text', models.CharField(max_length=500, verbose_name='text')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsurami.Note')),
            ],
        ),
    ]
